version: "3"
services:
  newman:
    image: postman/newman_ubuntu1404
    volumes: 
      - "~/depot/postman:/etc/newman"
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
 
  httpbin: 
    image: kennethreitz/httpbin
    ports: 
      - "80:8080"