version: "3"
services:
  newman:
    image: postman/newman_ubuntu1404
    links:
      - httpbin
    depends_on:
      - httpbin
    volumes: 
      - "~/depot/postman:/etc/newman"
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
 
  httpbin: 
    image: kennethreitz/httpbin
    ports: 
      - "8080:8080"